spring:
  # 민감 정보 분리
  profiles:
    active: db, jwt

  #  JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    #  MySQL 설정
  datasource:
    url: ${url}
    username: ${adminname}
    password: ${password}
    driver-class-name: ${driver-class-name}

  #  JSP 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# mybatis(자동 의존성 주입을 사용하지 않는 경우)
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}